.\" Manpage for sfArk-extractor.
.\" Contact maltouzes@gmail.com to correct errors or typos.
.TH sfark-extractor 1 "11 Apr 2017" "1.0" "sfark-extractor man page"
.SH NAME
sfark-extractor \- Simple graphical sfArk decompressor to sf2.
.SH SYNOPSIS
sfark-extractor
.SH DESCRIPTION
Converts legacy sfArk files into the SoundFont 2 format.
It is based on the library sfarklib, which unfortunately only supports
sfArk V2+ files.
.SH OPTIONS
The sfark-extractor does not take any options.
.SH SEE ALSO
sfarkxtc(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Tony Maillefaud (maltouzes@gmail.com)


