#!/bin/sh
# -*- coding: utf-8 -*-
################################################################################
# copyright 2016-2017 Tony Maillefaud <maltouzes@gmail.com>                    #
#                                                                              #
# This file is part of sfark-extractor                                         #
#                                                                              #
# sfark-extractor is free software: you can redistribute it and/or modify      #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation, either version 3 of the License, or            #
# (at your option) any later version.                                          #
#                                                                              #
# sfark-extractor is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with sfark-extractor If not, see <http://www.gnu.org/licenses/>.       #
################################################################################

python3 sample/sfark_extractor
